# Generated by Django 5.0.1 on 2024-05-31 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('subLocation', models.CharField(max_length=255)),
                ('part', models.CharField(max_length=255)),
                ('kind', models.IntegerField(choices=[(0, 'Vibration'), (1, 'Temperature'), (2, 'Humidity'), (3, 'TemperatureHumidity'), (4, 'Current')])),
                ('index', models.IntegerField()),
                ('isOnline', models.BooleanField(default=False)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('time', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.sensor')),
            ],
        ),
    ]
