# Generated by Django 2.2.5 on 2023-12-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorvalue',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
