# Generated by Django 5.0.1 on 2024-06-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='sensorvalue',
            old_name='time',
            new_name='timestamp',
        ),
    ]
