# Generated by Django 5.0.1 on 2024-06-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0002_rename_time_sensor_timestamp_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sensorvalue',
            index=models.Index(fields=['sensor_id'], name='mqtt_sensor_sensor__01c873_idx'),
        ),
    ]
