# Generated by Django 2.2.5 on 2023-12-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0002_auto_20231211_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensorType',
            field=models.IntegerField(choices=[(0, 'Vibration'), (1, 'Temperature'), (2, 'Humidity'), (3, 'TemperatureHumidity'), (4, 'Current'), ('Vibration', 0), ('Temperature', 1), ('Humidity', 2), ('TemperatureHumidity', 3), ('Current', 4)]),
        ),
    ]
