# Generated by Django 2.2.5 on 2023-12-18 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0003_auto_20231212_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorValueFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueType', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='media/')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.Sensor')),
            ],
        ),
    ]
