# Generated by Django 2.2.5 on 2023-12-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0004_sensorvaluefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorvaluefile',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
