# Generated by Django 5.0.1 on 2024-06-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0004_alter_sensorvalue_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensorvalue',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sensorvalue',
            constraint=models.UniqueConstraint(fields=('sensor', 'timestamp'), name='unique_sensor_timestamp'),
        ),
    ]
