# Generated by Django 2.2.5 on 2023-12-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0005_auto_20231228_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorvaluefile',
            name='file',
            field=models.FileField(max_length=200, upload_to='data/'),
        ),
    ]
