# Generated by Django 5.0.1 on 2024-06-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0006_remove_sensorvalue_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorvalue',
            name='kind',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorvalue',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
