# Generated by Django 2.2.5 on 2023-12-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0006_auto_20231228_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
