# Generated by Django 5.0.1 on 2024-02-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0008_alter_sensor_id_alter_sensorvalue_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorvalue',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
