# Generated by Django 5.0.1 on 2024-06-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0009_remove_sensorvalue_mqtt_sensor_sensor__01c873_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sensorvalue',
            name='mqtt_sensor_sensor__9ec326_idx',
        ),
        migrations.AddIndex(
            model_name='sensorvalue',
            index=models.Index(fields=['sensor_id', 'timestamp', 'kind'], name='mqtt_sensor_sensor__c1b3da_idx'),
        ),
    ]
