# Generated by Django 5.0.1 on 2024-05-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0010_rename_sensorindex_sensor_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='type',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='sensorvalue',
            old_name='type',
            new_name='kind',
        ),
    ]
