# Generated by Django 5.0.1 on 2024-05-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0011_rename_type_sensor_kind_rename_type_sensorvalue_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorvaluefile',
            old_name='valueType',
            new_name='valueKind',
        ),
    ]
