# Generated by Django 4.1 on 2024-05-30 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mqtt", "0012_rename_valuetype_sensorvaluefile_valuekind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensorvaluefile",
            name="sensor",
        ),
        migrations.DeleteModel(
            name="SensorValue",
        ),
        migrations.DeleteModel(
            name="SensorValueFile",
        ),
    ]
