# Generated by Django 4.1 on 2024-05-30 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mqtt", "0013_remove_sensorvaluefile_sensor_delete_sensorvalue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField()),
                ("time", models.DateTimeField()),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mqtt.sensor"
                    ),
                ),
            ],
        ),
    ]
